name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

